config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # get 'rooms/item_create'
  # get 'rooms/item_destroy'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/create'
  # get 'home/top'
  get 'home/index'
  # get 'users/edit'
  # get 'users/show'
  # get 'users/update'
  # get 'items/edit'
  # get 'items/show'
  # get 'items/update'
  # get 'items/create'
  # get 'items/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # home
  root to: 'home#top'

  # users
  resources :users, only: [:show, :edit, :update]
  # items
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
  # search
  get 'search', to: 'search#index', as: :search_index
  # rooms
  resources :rooms, only: [:new, :create, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

	belongs_to :user
	has_many :rooms, through: :rooms_items, dependent: :destroy
	has_many :rooms_items
	has_many :tags, dependent: :destroy

	accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
	# mount_uploader :item_image, ImagesUploader
	attachment :item_image

	  # Search method
  def self.get_movie(ky)
    if ky
      str = 'https://www.youtube.com/embed/' << ky
    else
      str = ''
    end
    return str
  end
end

app/models/room.rb
class Room < ApplicationRecord

	belongs_to :user
	has_many :items, through: :rooms_items
	has_many :rooms_items, dependent: :destroy
	attachment :room_image
end

app/models/rooms_item.rb
class RoomsItem < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :item
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :follows, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def index
  	@items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def edit
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.category.nil?
      @item.category = 1
    end
    if @item.category == 2
      @item.url = Item.get_movie(@item.url)
    end

    if @item.save
      # render json: {message: 'success', itemId: @item.id}, status: 200
      render :new
    else
      # render json: { error: @item.errors.full_messages.join(", ")}, status: 400
      render :new
    end
  end

  def new
    @item = Item.new
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to user_path
  end

  private
  # def item_params
  #   params.require(:item).permit(
  #     :user_id, :title, :caption, :category, :item_image, :url,
  #     tags_attributes: [:id, :item_id, :tag_title, :tag_type_id, :_destroy])
  # end

  def item_params
   params.require(:item).permit(
   :user_id, :title, :caption, :category, :item_image, :url)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def item_create
  end

  def item_destroy
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    @room.save
    redirect_to user_path(current_user.id)
  end

  private
  def room_params
    params.require(:room).permit(
     :room_name, :room_image)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    home_index_path
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  	@user = User.find(params[:id])
  end

  def show
    @items = Item.where(user_id: current_user.id)
    @rooms = Room.where(user_id: current_user.id)
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(
    	:name, :introduction, :email, :profile_image, :header_image)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_post.erb
  <%= form_for item, html: {class:'dropzone', id: "item-dropzone"} do |i| %>
    <div class=" needsclick" style="background-color: orange">
      <h3>Drop file here</h3> or
      <strong>Click</strong> to upload
    </div>
    <div class="fallback">
      <%= i.file_field :item_image %>
      <%= i.submit 'upload the image' %>
    </div>
  <% end %>
</div>

app/views/items/_post_image.erb
<!-- movie post -->
<!-- Form section -->
<%= form_for item, url: items_path do |f| %>
<!-- Error messages -->
<div class="form" >
  <div class=" mt-3" >

  <div class="form-group">
   <%= f.attachment_field :item_image, placeholder: "item_image" %>
  </div>

  <div class="form-group">
   <%= f.text_field :url, class: "form-control", placeholder: "URLを設定する" %>
  </div>

  <div class="form-group">
   <%= f.text_field :title, class: "form-control", placeholder: "タイトルを設定" %>
  </div>

  <div class="form-group">
   <%= f.text_area :caption, class: "form-control", placeholder: "紹介文を追加" %>
  </div>

  <div class="form-group">
   <%= f.hidden_field :category, value: 1 %>
  </div>

 </div>
 <div class="row form-action offset-4 my-5 col-md-4">
  <%= f.submit "投稿する", class: "btn btn-lg btn-warning btn-block" %>
 </div>
</div>
<% end %>

app/views/items/_post_images.erb
<div class="mt-3">
  <%= form_for item, html: {class:'dropzone', id: "item-dropzone"} do |f| %>
    <div class="dz-message needsclick">
      ドラッグ&ドロップで画像をアップロード
    </div>
    <div class="fallback">
      <%= f.attachment_field :item_image, class: "form-file-input", placeholder: "item_image" %>
      <%= f.submit 'upload the image' %>
    </div>
  <% end %>
</div>

app/views/items/_post_movie.erb
<!-- movie post -->
<!-- Form section -->
<%= form_for item, url: items_path do |f| %>
<!-- Error messages -->
<div class="form" >
  <div class="mt-3" >

  <div class="form-group">
   <%= f.text_field :url, class: "form-control", placeholder: "YouTubeのURLを入力　Ex:https://www.youtube.com/watch?v=○○○ " %>
  </div>

  <div class="form-group">
   <%= f.text_field :title, class: "form-control", placeholder: "タイトルを設定" %>
  </div>

  <div class="form-group">
   <%= f.text_area :caption, class: "form-control", placeholder: "紹介文を追加" %>
  </div>

  <div class="form-group">
   <%= f.hidden_field :category, value: 2 %>
  </div>

 </div>
 <div class="row form-action offset-4 my-5 col-md-4">
  <%= f.submit "投稿する", class: "btn btn-lg btn-warning btn-block" %>
 </div>
</div>
<% end %>

app/views/items/_tag_fields.html.erb
  <span>
    <%= f.text_field :tag_title, placeholder: "タグを入力", class: "form-control" %>
  </span>
  <span><%= link_to_remove_association 'remove', f, class: "btn" %>
  </span>
  <% f.text_field :tag_type_id, :value => 1, class: "form-control" %>

app/views/items/_tile_items.html.erb
<%= stylesheet_link_tag 'tile' %>
<div class="container-fluid my-2">
   <div class="grid" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 280, "fitWidth": true, "gutter": 25 }'>
    <% items.each do |i| %>

    <!-- 画像表示 -->
    <% if i.category == 1 %>
      <div class="grid-item" >
        <%= link_to item_path(i.id), method: :get do %>
       <p class="image"><%= attachment_image_tag i, :item_image, width: 280,  fallback: 'wallpaper/thom-holmes-556804-unsplash.jpg', class: "item " %></p>
       <% end %>
       <p class="caption">
        <%= i.title%>
        <div class="menu">
         <i class="fas fa-ellipsis-h"></i>
        </div>
       </p>
      </div>

    <!-- 動画表示 -->
    <% elsif i.category == 2 %>
      <div class="grid-item">
       <div class="movie-flame">
        <iframe width="565" height="280" src="<%= i.url%>" frameborder="100" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="item"></iframe>
       </div>
       <p class="caption" >
        <%= i.title%>
        <div class="menu">
         <i class="fas fa-ellipsis-h"></i>
        </div>
       </p>
      </div>

    <% end %>
    <% end %>

   </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/new.html.erb
<%= stylesheet_link_tag 'items' %>
<%= javascript_include_tag 'items' %>
<div class="container" >
  <div class="row justify-content-md-center mb-lg-5">
    <div class="col-md-9 mx-auto" >
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="row justify-content-md-center">
        <h2>アイテムを投稿</h2>
      </div>
      	<!-- tab -->
	   <div class="p-3">
  		 <!-- タブボタン部分 -->
 		 <ul class="nav nav-tabs justify-content-md-center">
    	  <li class="nav-item">
      	   <a href="#tab1" class="nav-link active" data-toggle="tab"><i class="far fa-image"></i></a>
    	  </li>
    	  <li class="nav-item">
      		<a href="#tab2" class="nav-link" data-toggle="tab"><i class="fab fa-youtube"></i></a>
    	  </li>
    	  <li class="nav-item">
      		<a href="#tab3" class="nav-link" data-toggle="tab"><i class="fas fa-images"></i></i></a>
    	  </li>
  		 </ul>

  		 <!--タブのコンテンツ部分-->
  		 <div class="tab-content">
    	  <div id="tab1" class="tab-pane active">
	 	     <%= render "items/post_image", item: @item %>
    	  </div>
    	  <div id="tab2" class="tab-pane">
      	   <%= render "items/post_movie", item: @item %>
    	  </div>
    	  <div id="tab3" class="tab-pane">
      	   <%= render "items/post_images", item: @item %>
    	  </div>
  	     </div>
	  </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<%= stylesheet_link_tag 'items' %>
<div class="container mt-5">
 <div class="row mt-5">
  <!-- 画像 -->
  <div class="image-box col-md-6">
  	<!-- 画像 -->
  	<%= attachment_image_tag @item, :item_image, width: 450, fallback: 'wallpaper/thom-holmes-556804-unsplash.jpg',  class: "room-image" %>

  	<!-- リンク画像 -->

  	<!-- 動画 -->
  </div>

  <!-- タイトル・説明文 -->
  <div class="col-md-6 mt-4">
   <table class="table table-borderless ">
    <tbody>
      <tr>
        <th>タイトル</th>
        <td><strong><%= @item.title %></strong></td>
      </tr>
      <tr>
        <th>説明文</th>
        <td><%= @item.caption %></td>
      </tr>
      <tr>
        <th>URL</th>
        <td><%= @item.url %></td>
      </tr>
    </tbody>
  </table>
  <div class="row">
   <%= link_to "削除", item_path(@item.id), method: :delete, class: "btn btn-danger" %><br>
  </div>
  </div>
 </div>
</div>

app/views/rooms/new.html.erb
<div class="container mt-5">
 <div class="row offset-4 col-md-5 form-group">
  <p><h1>ルームを作成する</h1></p>
 </div>
 <%= form_for @room, url: rooms_path do |f| %>

  <div class="form-group offset-3 col-md-6 ">
   <%= attachment_image_tag @room, :room_image, :fill, 100, 100, format: "jpg", :size => "100x100", fallback: "wallpaper/thom-holmes-556804-unsplash.jpg" %>
   <%= f.attachment_field :room_image, placeholder: "profile_image" %>
  </div>

  <div class="form-group offset-3 col-md-6 ">
   <%= f.text_field :room_name, class: "form-control", placeholder: "ルーム名を入力" %>
  </div>
  <div class="row form-action offset-4 col-md-4 form-group">
   <%= f.submit "ルームを作成する", class: "btn btn-lg btn-warning btn-block" %>
  </div>
 <% end %>
</div>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>