config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # get 'rooms/item_create'
  # get 'rooms/item_destroy'
  # get 'rooms/show'
  # get 'rooms/new'
  # get 'rooms/create'
  # get 'home/top'
  get 'home/index'
  # get 'users/edit'
  # get 'users/show'
  # get 'users/update'
  # get 'items/edit'
  # get 'items/show'
  # get 'items/update'
  # get 'items/create'
  # get 'items/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # home
  root to: 'home#top'

  # users
  resources :users, only: [:show, :edit, :update]
  # items
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
  # search
  get 'search', to: 'search#index', as: :search_index
  # rooms
  resources :rooms, only: [:new, :create, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

	belongs_to :user
	has_many :rooms, through: :rooms_items, dependent: :destroy
	has_many :rooms_items
	has_many :tags, dependent: :destroy

	accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
	# mount_uploader :item_image, ImagesUploader
	attachment :item_image

	  # Search method
  def self.get_movie(ky)
    if ky
      str = 'https://www.youtube.com/embed/' << ky
    else
      str = ''
    end
    return str
  end
end

app/models/room.rb
class Room < ApplicationRecord

	belongs_to :user
	has_many :items, through: :rooms_items
	has_many :rooms_items, dependent: :destroy
	attachment :room_image
end

app/models/rooms_item.rb
class RoomsItem < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :item
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :follows, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def index
  	@items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def edit
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.category.nil?
      @item.category = 1
    end
    if @item.category == 2
      @item.url = Item.get_movie(@item.url)
    end

    if @item.save
      # render json: {message: 'success', itemId: @item.id}, status: 200
      render :new
    else
      # render json: { error: @item.errors.full_messages.join(", ")}, status: 400
      render :new
    end
  end

  def new
    @item = Item.new
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to user_path
  end

  private
  # def item_params
  #   params.require(:item).permit(
  #     :user_id, :title, :caption, :category, :item_image, :url,
  #     tags_attributes: [:id, :item_id, :tag_title, :tag_type_id, :_destroy])
  # end

  def item_params
   params.require(:item).permit(
   :user_id, :title, :caption, :category, :item_image, :url)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def item_create
  end

  def item_destroy
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    @room.save
    redirect_to user_path(current_user.id)
  end

  private
  def room_params
    params.require(:room).permit(
     :room_name, :room_image)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  	@user = User.find(params[:id])
  end

  def show
    @items = Item.where(user_id: current_user.id)
    @rooms = Room.where(user_id: current_user.id)
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(
    	:name, :introduction, :email, :profile_image, :header_image)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag 'navbar' %>
<%= javascript_include_tag 'navbar' %>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light bd-navbar shadow fixed-top py-1">
    <% unless user_signed_in? then%>
    <a class="navbar-brand mb-0 h1 ml-4" href="<%= root_path %>"><%= image_tag('logo/Homebase/flat.png',  class: 'logo-image') %></a>
    <% else %>
    <a class="navbar-brand mb-0 h1 ml-4" href="<%= home_index_path %>"><%= image_tag('logo/Homebase/flat.png',  class: 'logo-image') %></a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ml-5">
        <% if user_signed_in? then%>
        <!-- User section -->
         <!-- Search form -->
          <%= form_with url: search_index_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do |f| %>
            <%= f.text_field :keyword, palceholder: "search",class: "form-control form-control-sm mr-2", :size =>"100", :placeholder => "検索する" %>
            <%= f.submit '検索', class: 'btn btn-warning'%>
            <% end %>
            <li class="nav-item">
              <%= link_to new_item_path, method: :get, class: 'nav-link' do %>
              <div class="icon" href="javascript:void(0);" id="popover" data-toggle="popover" data-placement="top" title="アイテム作成">
                <i class="fas fa-plus"></i>
              </div>
              <% end %>
            </li>
      </ul>
      <ul class="navbar-nav ml-5">
          <li class="nav-item">
            <%= link_to user_path(current_user.id), method: :get, class: 'nav-link' do %>
              <div class="icon" href="javascript:void(0);" id="popover" data-toggle="popover" data-placement="top" title="マイページ">
                <%= attachment_image_tag current_user, :profile_image, :fill, 200, 200, :size => "40x40", fallback: "no-user-image.jpg",class: 'user-image' %>
              </div>
            <% end %>
          </li>
          <li class="nav-item">
            <div class="icon">
             <i class="fas fa-bars menu__icon"></i>
            </div>
          </li>
        </ul>
        <!-- sidebar -->
           <aside class="sidebar">
            <div class="sidebar__inner">
             <h2 class="sidebar__ttl">Menu</h2>
             <i class="fas fa-times-circle sidebar__icon"></i>
            </div>
            <p class="sidebar__txt"><%= link_to edit_user_path(current_user.id), method: :get, class: 'nav-link' do %>
                <i class="fas fa-user-edit"></i></i>ユーザー情報
            <% end %></p>
             <p class="sidebar__txt"><%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                <i class="fas fa-sign-out-alt fa-lg" ></i>logout
            <% end %></p>
           </aside>
          <!--  未ログイン -->
        <% else %>

      </ul>
        <ul class="navbar-nav ml-5">
          <li class="nav-item" >
            <a class="nav-link " href="<%= new_user_session_path %>">
              <div class="icon" href="javascript:void(0);" id="popover" data-toggle="popover" data-placement="top" title="ログインする">
                <i class="fas fa-sign-in-alt fa-lg"></i>
              </div>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">
              <div class="icon" href="javascript:void(0);" id="popover" data-toggle="popover" data-placement="top" title="新規登録">
                <i class="fas fa-user-plus fa-lg"></i>
              </div>
            </a>
          </li>
        </ul>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homebase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.2/css/swiper.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <!-- js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.2.2/js/swiper.min.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- Header Navbar -->
    <%= render "layouts/navbar" %>
    <!-- Main Content -->
    <%= yield %>


  </body>
  <!-- Footer -->
  <footer class="justify-content-center fixed-bottom" id="footer" style="; position: relative;">
    <p class="text-secondary">© 2019 Copyright Text</p>
  </footer>
</html>